### ISSUE TITLE
Where is hapi-config??

### ISSUE THREAD

**Issue by AdrieanKhisbe** [Pagemesh/hapi-config#2]
Installing `hapi-config` from npm we get version `0.1.4) with hash https://github.com/Pagemesh/hapi-config/commit/129b88ecf444e00d061322639973415743458d6e.

Where it is?, 
It's on any branch (but still accessible from github)

**Comment by jgrenon** [comment]
Sorry for the confusion, I'm maintaining this package mostly through customer projects and the latest branch is in my company account : https://github.com/Covistra/hapi-config. I'll make sure to update my package.json to correct this confusion

**Comment by AdrieanKhisbe** [comment]
Indeed!
Seems like I forked te wrong hapi-config. :)

**Comment by jgrenon** [comment]
Version 0.1.5 should now be in npm and point to the right repo!

**Comment by AdrieanKhisbe** [comment]
okey dokey :)

**Comment by AdrieanKhisbe** [comment]
why can't you upgrade Pagemesh page so it's up to date?
This would avoid confusion

**Comment by AdrieanKhisbe** [comment]
(or at least make this page point to the new *master* repositery :) )
