### ISSUE TITLE
Some explanation for a beginner

### ISSUE THREAD

**Issue by rapsli** [Pagemesh/hapi-config#3]
Just started out with 

`server.register({register:` require('./')}, function(err){});

I don't understand the require('./') part. Wouldn't I need to specify which plugin I'm registering, e.g. hapi-config?

**Comment by jgrenon** [comment]
Yes, just replace with hapi-config in your app. We use ./ because we are directly in the hapi-config module.

**Comment by rapsli** [comment]
aha ;)

and 

`var config = server.plugins['config'].CurrentConfiguration;`

"config" would be your json file? and what would CurrentConfiguration be?

Thanks a lot for the patience.

**Comment by jgrenon** [comment]
config will be your nconf instance, with all environment, local, test and general config files resolved. You can access your config elements using get (see nconf for more details).

**Comment by rapsli** [comment]
ok.

var config = server.plugins['config'].CurrentConfiguration;
-> error

var config = server.plugins['hapi-config'].CurrentConfiguration;
-> works

not sure if it's my system or the documentation.
